// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ3ChqJ8m7ojtQyY7vvPo5pfVhX1ZAgv8',
    appId: '1:1086072201157:web:04fac115e5c73786bfb5ac',
    messagingSenderId: '1086072201157',
    projectId: 'bemyinterpreter',
    authDomain: 'bemyinterpreter.firebaseapp.com',
    databaseURL: 'https://bemyinterpreter-default-rtdb.firebaseio.com',
    storageBucket: 'bemyinterpreter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGj0iG34mfLmx9s1ma8fdZIhJ7TfHdDlI',
    appId: '1:1086072201157:android:281c448de8d304b9bfb5ac',
    messagingSenderId: '1086072201157',
    projectId: 'bemyinterpreter',
    databaseURL: 'https://bemyinterpreter-default-rtdb.firebaseio.com',
    storageBucket: 'bemyinterpreter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9I1zzY5mom5kT4IbrdTofSvgtXGzQEuc',
    appId: '1:1086072201157:ios:e9bca8011f4cbdb6bfb5ac',
    messagingSenderId: '1086072201157',
    projectId: 'bemyinterpreter',
    databaseURL: 'https://bemyinterpreter-default-rtdb.firebaseio.com',
    storageBucket: 'bemyinterpreter.appspot.com',
    iosClientId: '1086072201157-c2aggis8jts5qb4lo49i6im9tva2l0d2.apps.googleusercontent.com',
    iosBundleId: 'com.memoire.bemyinterprete',
  );
}
